In [3]:
import torch
import numpy as np

### Creating tensor Using Multiple Methods

In [4]:
## Normally
a=torch.tensor([2,3,4])

In [5]:
type(a)

torch.Tensor

In [6]:
## from npy array
np_arr=np.array([2,3,4])
torch_arr=torch.tensor(np_arr)

Empty allocates memory to tensor but doesnt initialize it by any value. But it prints garbage value without storing on memory

In [7]:
## using empty
a=torch.empty(2,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
torch.empty_like(torch_arr)

tensor([0, 0, 0])

In [9]:
### using zeroes
shape=(2,3)
torch.zeros(shape)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
torch.zeros_like(torch_arr)

tensor([0, 0, 0])

In [11]:
## Using ones
torch.ones(shape)
torch.ones_like(torch_arr)

tensor([1, 1, 1])

In [12]:
## using rand
torch.rand(shape)

tensor([[0.6291, 0.6960, 0.6387],
        [0.1741, 0.8148, 0.4552]])

In [13]:
## we have to mention dtype of tensor as float as rand genrate vaue from 0 to 1
torch.rand_like(torch_arr,dtype=torch.float16)

tensor([0.8491, 0.2686, 0.7466], dtype=torch.float16)

In [14]:
## tensor with seeding for reproducebility
torch.manual_seed(2)
torch.rand(2,3)

tensor([[0.6147, 0.3810, 0.6371],
        [0.4745, 0.7136, 0.6190]])

In [15]:
## other
torch.arange(0,9,2)

tensor([0, 2, 4, 6, 8])

In [16]:
torch.linspace(-2,2,10)

tensor([-2.0000, -1.5556, -1.1111, -0.6667, -0.2222,  0.2222,  0.6667,  1.1111,
         1.5556,  2.0000])

In [17]:
torch.eye(5) 

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [18]:
torch.full((4,4),5)
##   torch.full_like()

tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])