In [29]:
import torch

### Basic Math Operation on single tensor

In [30]:
arr=torch.rand((2,3))
arr

tensor([[0.2735, 0.0694, 0.3262],
        [0.3841, 0.0598, 0.7416]])

Scalar Operation (very basics)

In [31]:
arr+1

tensor([[1.2735, 1.0694, 1.3262],
        [1.3841, 1.0598, 1.7416]])

In [32]:
arr*2

tensor([[0.5470, 0.1388, 0.6525],
        [0.7683, 0.1195, 1.4832]])

In [33]:
arr-1

tensor([[-0.7265, -0.9306, -0.6738],
        [-0.6159, -0.9402, -0.2584]])

In [34]:
arr**3

tensor([[2.0455e-02, 3.3400e-04, 3.4723e-02],
        [5.6685e-02, 2.1332e-04, 4.0786e-01]])

In [35]:
arr%0.5

tensor([[0.2735, 0.0694, 0.3262],
        [0.3841, 0.0598, 0.2416]])

In [36]:
arr>1

tensor([[False, False, False],
        [False, False, False]])

In [37]:
## sum of all numbers on tensor
torch.sum(arr)

tensor(1.8546)

In [38]:
## product of numbers
torch.prod(arr)

tensor(0.0001)

In [39]:
a=torch.tensor([2.4,-3.5,4,-9])

In [40]:
torch.abs(a)

tensor([2.4000, 3.5000, 4.0000, 9.0000])

In [41]:
torch.neg(a)

tensor([-2.4000,  3.5000, -4.0000,  9.0000])

In [42]:
torch.round(a)

tensor([ 2., -4.,  4., -9.])

Some usefull operations

In [44]:
## apply ceiling and floor function
torch.ceil(a)

tensor([ 3., -3.,  4., -9.])

In [46]:
torch.floor(a)

tensor([ 2., -4.,  4., -9.])

In [48]:
## if values are smaller or greater than given range change to boundary value
torch.clamp(a,min=2,max=5)

tensor([2.4000, 2.0000, 4.0000, 2.0000])

In [54]:
b=torch.tensor([[1,2,3],[9,1,0]],dtype=torch.float16)

In [50]:
torch.sum(b)

tensor(16)

In [51]:
torch.sum(b,dim=0)


tensor([10,  3,  3])

In [52]:
torch.sum(b,dim=1)

tensor([ 6, 10])

In [55]:
torch.mean(b,dim=0)

tensor([5.0000, 1.5000, 1.5000], dtype=torch.float16)

In [59]:
print(f"Median is{torch.median(b)}")
print(f"Max is{torch.max(b)}")
print(f"Min is{torch.min(b)}")
print(f"Standard Deviation is{torch.std(b)}")
print(f"Variance is{torch.var(b)}")
print(f"Postion of max value in tensor is {torch.argmax(b)}")

Median is1.0
Max is9.0
Min is0.0
Standard Deviation is3.265625
Variance is10.6640625
Postion of max value in tensor is 3
