In [51]:
import torch

In [52]:
vect1=torch.tensor([32,43,26,22])
vect2=torch.tensor([32,43,26,22],dtype=float)

### In-Place Operation <br>
An in-place operation in PyTorch  is an operation that modifies the contents of a tensor directly in memory, instead of creating a new tensor.
<br> <br> Suppose we want to apply relu activation on a tensor and store it back to that tensor <br>
#### Instead of doing

In [53]:
vect1=torch.sigmoid(vect1)
vect1

tensor([1., 1., 1., 1.])

#### We do

In [54]:
vect2.sigmoid_()

tensor([1.0000, 1.0000, 1.0000, 1.0000], dtype=torch.float64)

#### To perform In-place operation on any tensor we do <br>
tensor.function_()
eg: vect=torch.tensor([1,3,4,3]) <br>
vect.sum_(3)<br>
vect.relu_()<br>
vect.sigmoid_()<br>

In [55]:
vect=torch.tensor([1,3,4,3],dtype=torch.float32)
vect.add_(1)

tensor([2., 4., 5., 4.])

#### Cloning 2 tensors

##### New memory location of b is not created rather a and b point to same memory reference

In [56]:
### wihtout cloning
a=torch.tensor([1,2,3])
b=a
a[0]=-1
b

tensor([-1,  2,  3])

##### New memory location of b is not created rather a and b point to same memory reference

In [57]:
id(a)-id(b)

0

In [58]:
### with cloning
a=torch.tensor([1,2,3])
b=a.clone()
a[0]=-1
b

tensor([1, 2, 3])

##### New Memory location of b is created

In [59]:
id(a)-id(b)

7920