In [66]:
import torch

### Math Operation on 2 tensors

#### Basics

In [67]:
a=torch.rand((2,3))
b=torch.rand((2,3))

In [68]:
a+b
a*b
a**b
a//b

tensor([[0., 0., 0.],
        [0., 0., 1.]])

#### Matrix Operation

In [69]:
#mutipication
mat1=torch.rand((2,3))
mat2=torch.rand((3,2))
torch.matmul(mat1,mat2)

tensor([[0.8961, 1.7747],
        [0.7648, 1.3096]])

In [70]:
sqr_mat=torch.tensor([[1,2,3], [3,4,9], [3,4,2]],dtype=torch.float32)

In [71]:
torch.det(sqr_mat)

tensor(14.)

In [72]:
torch.inverse(sqr_mat)

tensor([[-2.0000e+00,  5.7143e-01,  4.2857e-01],
        [ 1.5000e+00, -5.0000e-01,  0.0000e+00],
        [ 2.9802e-08,  1.4286e-01, -1.4286e-01]])

In [73]:
torch.linalg.eig(sqr_mat)

torch.return_types.linalg_eig(
eigenvalues=tensor([10.6112+0.j, -0.4125+0.j, -3.1988+0.j]),
eigenvectors=tensor([[ 0.3213+0.j,  0.7881+0.j, -0.0951+0.j],
        [ 0.8111+0.j, -0.6143+0.j, -0.7617+0.j],
        [ 0.4887+0.j,  0.0385+0.j,  0.6409+0.j]]))

In [74]:
## dot product
vector1=torch.tensor([1,9,4])
vector2=torch.tensor([3,2,7])
torch.dot(vector1,vector2)

tensor(49)

#### Special Operation

In [75]:
tns=torch.tensor([2,3,7],dtype=torch.float32)

Math operation

In [76]:
torch.log(tns)

tensor([0.6931, 1.0986, 1.9459])

In [77]:
torch.exp(tns)

tensor([   7.3891,   20.0855, 1096.6332])

Activation Function

In [78]:
torch.sigmoid(tns)

tensor([0.8808, 0.9526, 0.9991])

In [79]:
torch.tanh(tns)

tensor([0.9640, 0.9951, 1.0000])

In [80]:
torch.softmax(tns,dim=0)

tensor([0.0066, 0.0179, 0.9756])